server:
  port: 9000
eureka:
  client.serviceUrl.defaultZone: http://eureka:8761/eureka
  instance:
    app-group-name: microservices
    appname: amazin-client
spring:
  rabbitmq:
    host: rabbit
    addresses: rabbit:5672
