server:
  port: 8004
spring:
  jpa:
    database: H2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:authdb
    driverClassName: org.h2.Driver
    username: sa
    password:
