spring:
  datasource:
    url: jdbc:mysql://db:3306/booksservice?useUnicode=true&characterEncoding=utf8&useSSL=false
    name:
    username: root
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: rabbit
    addresses: rabbit:5672
eureka:
  client.serviceUrl.defaultZone: http://eureka:8761/eureka
  instance:
    app-group-name: microservices
    hostname: eureka
    appname: books-service
cache: # Hibernate 2nd level cache, used by CacheConfiguration
    hazelcast:
        timeToLiveInSeconds: 3600
