server:
  port: 8011
spring:
  jpa:
    show-sql: true
  rabbitmq:
    host: rabbit
    addresses: rabbit:5672
eureka:
  client.serviceUrl.defaultZone: http://eureka:9000/eureka
  instance:
    app-group-name: microservices
    hostname: eureka
    appname: comments-service
