server:
  port: 8011
spring:
  jpa:
    show-sql: true
eureka:
  client.serviceUrl.defaultZone: http://localhost:9000/eureka
  instance:
    app-group-name: microservices
    hostname: localhost
    appname: comments-service
