spring:
  cloud:
    config:
      server:
        git:
          force-pull: true          
        default-application-name: default-application-name
eureka:
  client.serviceUrl.defaultZone: http://localhost:9000/eureka
  instance:
    app-group-name: microservices
    hostname: localhost
    appname: config-server
server:
  port: 8888
