server:
  port: 9000
spring:
  rabbitmq:
    host: rabbit
    addresses: rabbit:5672
eureka:
  instance:
    hostname: eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
