server:
  port: 8003
spring:
  jpa:
    database: H2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:recommendationsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
hazelcast:
  enabled: false
