server:
  port: 8002
eureka:
  client.serviceUrl.defaultZone: http://eureka:8761/eureka
  instance:
    app-group-name: microservices
    appname: recommendations-service
spring:
  rabbitmq:
    host: rabbit
    addresses: rabbit:5672
